# This is a basic workflow to help you get started with Actions

name: Lint Code Base

# Controls when the action will run.
on: push


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Name the Job
    name: Linter flake8
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v3.11.0
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # VALIDATE_PYTHON: true
          VALIDATE_PYTHON_FLAKE8: true
          # VALIDATE_PYTHON_PYLINT: false
